services:
  - type: web
    name: http-monitor-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/monitor/responses
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
